apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-test-docker-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-test-docker-k8s
  template:
    metadata:
      labels:
        app: spring-boot-test-docker-k8s
    spec:
      containers:
        - name: spring-boot-test-docker-k8s
          image: nensiskenderi/spring-boot-test-docker-k8s:v0.0.1
          ports:
            - containerPort: 8080
